package com.healthcare.app.domain

data class FeatureParityItem(
    val webPath: String,
    val androidRoute: String,
    val group: String,
    val nativeStatus: String,
)

object FeatureParity {
    val items = listOf(
        FeatureParityItem("/", "dashboard", "Core", "native"),
        FeatureParityItem("/hospitals", "hospitals", "Core", "native-list"),
        FeatureParityItem("/hospital/:id", "hospitals", "Core", "native-detail-pending"),
        FeatureParityItem("/patients", "patients", "Core", "native-list"),
        FeatureParityItem("/patients/:id", "patients", "Core", "native-detail-pending"),
        FeatureParityItem("/appointments", "appointments", "Core", "native-list"),
        FeatureParityItem("/video-meet", "video_meet", "Video", "native-list-token-pending"),
        FeatureParityItem("/queue", "queue", "Core", "native-list"),
        FeatureParityItem("/history", "history", "Core", "offline-parity"),
        FeatureParityItem("/records", "records", "Core", "offline-parity"),
        FeatureParityItem("/receipts", "receipts", "Core", "offline-parity"),
        FeatureParityItem("/telemetry/overview", "telemetry_overview", "Telemetry", "api-backed"),
        FeatureParityItem("/telemetry/live", "telemetry_live", "Telemetry", "api-backed"),
        FeatureParityItem("/telemetry/devices", "telemetry_devices", "Telemetry", "api-backed"),
        FeatureParityItem("/telemetry/assignments", "telemetry_assignments", "Telemetry", "api-backed"),
        FeatureParityItem("/prescribe", "prescribe", "Pharmacy", "offline-parity"),
        FeatureParityItem("/medicines", "medicines", "Pharmacy", "offline-parity"),
        FeatureParityItem("/medicine-orders", "medicine_orders", "Pharmacy", "api-backed"),
        FeatureParityItem("/prescription-orders", "prescription_orders", "Pharmacy", "api-backed"),
        FeatureParityItem("/pharmacy-stock", "pharmacy_stock", "Pharmacy", "offline-parity"),
        FeatureParityItem("/prescription-upload", "prescription_upload", "Pharmacy", "offline-parity"),
        FeatureParityItem("/prescription-verify", "prescription_verify", "Pharmacy", "offline-parity"),
        FeatureParityItem("/restock", "restock", "Pharmacy", "offline-parity"),
        FeatureParityItem("/inventory", "inventory", "Pharmacy", "api-backed"),
        FeatureParityItem("/insurance-renewal", "insurance_renewal", "Insurance", "offline-parity"),
        FeatureParityItem("/policies", "policies", "Insurance", "api-backed"),
        FeatureParityItem("/applicants", "applicants", "Insurance", "api-backed"),
        FeatureParityItem("/policy-status", "policy_status", "Insurance", "api-backed"),
        FeatureParityItem("/request-blood", "request_blood", "Blood bank", "offline-parity"),
        FeatureParityItem("/blood-requests", "blood_requests", "Blood bank", "offline-parity"),
        FeatureParityItem("/blood-inventory", "blood_inventory", "Blood bank", "offline-parity"),
        FeatureParityItem("/donation-requests", "donation_requests", "Blood bank", "offline-parity"),
        FeatureParityItem("/hospital-application", "hospital_application", "Hospital admin", "offline-parity"),
        FeatureParityItem("/hospital/doctors", "hospital_doctors", "Hospital admin", "offline-parity"),
        FeatureParityItem("/hospital/patients", "hospital_patients", "Hospital admin", "offline-parity"),
        FeatureParityItem("/hospital/pharmacy", "hospital_pharmacy", "Hospital admin", "offline-parity"),
        FeatureParityItem("/hospital/beds", "hospital_beds", "Hospital admin", "api-backed"),
        FeatureParityItem("/hospital/staff", "hospital_staff", "Hospital admin", "offline-parity"),
        FeatureParityItem("/hospital/billing", "hospital_billing", "Hospital admin", "offline-parity"),
        FeatureParityItem("/bed-availability", "bed_availability", "Hospital admin", "api-backed"),
        FeatureParityItem("/logs", "logs", "System", "api-backed"),
        FeatureParityItem("/profile", "profile", "Account", "native"),
    )
}
